### ISSUE TITLE
Make BreakTypes documentation more complete

### ISSUE THREAD

**Issue by Amine-Mike** [Faveod/oppen-ruby#10]
We should put ourselves in the mindset of a newcomer who barely knows how Oppen works, so our explanation needs to be:

1. Self-contained
2. Complete
3. Leaves no room for doubts.

_Originally posted by @stackmystack in https://github.com/Faveod/oppen-ruby/pull/8#discussion_r1756437959_

**Comment by stackmystack** [comment]
Addressed in https://github.com/Faveod/oppen-ruby/pull/47
